services:
  frankenphp:
    image: dunglas/frankenphp:php8.3
    restart: unless-stopped
    command: frankenphp run --config /etc/caddy/Caddyfile --watch
    ports:
      - "3979:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SERVER_NAME=:80
      - FRANKENPHP_CONFIG=worker ./public/index.php
    depends_on:
      - mariadb
      - redis
    networks:
      - workoflow

  mariadb:
    image: mariadb:11.2
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workoflow_db
      MYSQL_USER: workoflow
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - workoflow

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - workoflow

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - workoflow


volumes:
  mariadb_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  workoflow:
    driver: bridge
